_target_: src.models.mnist_module.MNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.best_model.ConvNet
  norm_layer: 

    _target_: torch.nn.GroupNorm
    _partial_: true




use_l1: false
regularizer:
  _target_: src.models.components.l1_reg.L1RegularizedConv2D
  weight_decay: 0.0001
  _partial_: true




